version: '3.8'
services:
  nginx: 
    image: library/nginx:1.19-alpine
    container_name: "project_nginx"
    ports:
      - 8787:80
    volumes:
      - "/home/ec2-user/project/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "/home/ec2-user/project/php/project:/var/www/html"
    links:
      - db
  php:
    build: /home/ec2-user/project/php
    container_name: "project_php"
    ports:
      - 9000:9000
    links:
      - db
  db:
   image: mysql:5.7
   ports:
     - 3306:3306
   environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: project
